version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: ConsoleM/docs/conf.py

python:
  install:
    - method: pip
      path: .
    - method: pip
      requirements: requirements.txt
    - sphinx-rtd-theme>=3.0.0 