name: Version Bump

on:
  push:
    branches: [ master ]
    paths:
      - 'ConsoleM/**'
      - 'setup.py'
      - '.github/workflows/version.yml'
  pull_request:
    branches: [ master ]

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Check for version bump
        id: check
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "bump=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Get the commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Check for version bump keywords
          if [[ $COMMIT_MSG == *"[major]"* ]]; then
            echo "bump=true" >> $GITHUB_OUTPUT
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG == *"[minor]"* ]]; then
            echo "bump=true" >> $GITHUB_OUTPUT
            echo "type=minor" >> $GITHUB_OUTPUT
          elif [[ $COMMIT_MSG == *"[patch]"* ]]; then
            echo "bump=true" >> $GITHUB_OUTPUT
            echo "type=patch" >> $GITHUB_OUTPUT
          else
            echo "bump=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Update version
        if: steps.check.outputs.bump == 'true'
        run: |
          python scripts/version.py ${{ steps.check.outputs.type }}
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add setup.py ConsoleM/__init__.py pyproject.toml
          git commit -m "chore: bump version to ${{ steps.check.outputs.type }}"
          git push 